.PHONY : run

run:
	./MakeLogo.py
	rsvg-convert pydwf-logo.svg -w 800 -h 500 -o pydwf-logo-800x500.png
	rsvg-convert pydwf-logo.svg -w 200 -h 125 -o pydwf-logo-200x125.png
	rsvg-convert pydwf-logo.svg -f pdf -o pydwf-logo.pdf
