#! /usr/bin/env python3

"""This script verifies the behavior of the AnalogIn instruments channel range settings."""

import numpy as np
import matplotlib.pyplot as plt

from pydwf import DwfLibrary

def main():

    dwf = DwfLibrary()

    with dwf.device.open(-1) as device:
        analogIn = device.analogIn

        analogIn.reset()

        channel_index = 0

        for attenuation in [1.0, 2.0, 5.0, 10.0, 0.0, -0.0, -1.0, -2.0, -5.0, -10.0]:
            analogIn.channelAttenuationSet(channel_index, attenuation)
            attenuation_readback = analogIn.channelAttenuationGet(channel_index)
            ch_offset = analogIn.channelOffsetGet(channel_index)
            ch_range  = analogIn.channelRangeGet(channel_index)
            print(attenuation, attenuation_readback, ch_offset, ch_range)

if __name__ == "__main__":
    main()

